vim.pack.add({ "https://github.com/ellisonleao/gruvbox.nvim.git" })

require("gruvbox").setup({
	transparent_mode = true,
})
vim.cmd.colorscheme("retrobox")

vim.api.nvim_set_hl(0, "StatusLine", { bg = "none" })
vim.api.nvim_set_hl(0, "TabLine", { bg = "none" })
vim.api.nvim_set_hl(0, "TabLineSel", { bg = "none" })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = "none" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "#111111" })
vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
vim.api.nvim_set_hl(0, "SignColumn", { bg = "none" })
vim.api.nvim_set_hl(0, "LineNr", { fg = "#ffffff", bold = true })
vim.api.nvim_set_hl(0, "LineNrAbove", { fg = "#abcabc" })
vim.api.nvim_set_hl(0, "LineNrBelow", { fg = "#abcabc" })
vim.api.nvim_set_hl(0, "Substitute", { reverse = true })
vim.api.nvim_set_hl(0, "IncSearch", { reverse = true })
vim.api.nvim_set_hl(0, "Visual", { reverse = true })
vim.api.nvim_set_hl(0, "Cursor", { reverse = true })
vim.api.nvim_set_hl(0, "WinSeparator", { bg = "none", fg = "#898989" })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#ffabab" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#ffffab" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#ababff" })
